package = "olexsmir.github.io"
version = "0.1.0"
lua = ">=5.1"

[description]
maintainer = "olex"

[run]
command = "nvim"
args = [ "-l", "lua/olexsmir/init.lua" ]

[build]
type = "builtin"

[dependencies]
# Add your dependencies here
# `busted = ">=2.0"`
