name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Install nvim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - uses: actions/checkout@v4

      - name: build
        run: nvim --clean -u ./minit.lua -l build.lua

      - name: push to site branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "{msg}"
