name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Install nvim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - uses: actions/checkout@v4

      - name: install chroma
        run: |
          wget https://github.com/alecthomas/chroma/releases/download/v2.20.0/chroma-2.20.0-linux-amd64.tar.gz
          tar -xzf chroma-2.20.0-linux-amd64.tar.gz
          sudo mv chroma /usr/local/bin/chroma
          chroma --version

      - name: build
        run: make build

      - name: push to site branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "{msg}"
