name: tests

on:
  push:
    branches:
    - main
    - develop
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install NeoVim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - uses: actions/checkout@v4

      - name: Cache .tests
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.tests
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-tests-${{ hashFiles('${{ github.workspace }}/.tests') }}

      - name: Run Tests
        run: |
          nvim --version
          make test
