name: tests

on:
  push:
    branches:
    - main
    - develop
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: install nvim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - uses: actions/checkout@v4

      - name: tests
        run: |
          nvim --version
          make test
